version: "2.2"
services:
  mysql:
    image: mysql:1
    build:
      context: .
      dockerfile: ./db/Dockerfile
    volumes:
        - ./db/db-data:/var/lib/mysql
    cpuset: "1"
    mem_reservation: "125M"
    mem_limit: "250M"
    restart: always
    networks:
       - weward_network
       
  wordpress:
    image: wordpress:1
    build:
      context: .
      dockerfile: ./wordpress/Dockerfile
    volumes:
        - ./wordpress:/var/www/html
    cpuset: "1"
    mem_reservation: "125M"
    mem_limit: "250M"
    links:
        - mysql
    restart: always
    networks:
       - weward_network
       
  nginx:
    image: nginx:1
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
   
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
    cpuset: "1"
    mem_reservation: "125M"
    mem_limit: "250M"    
    links:
        - wordpress
    restart: always
    networks:
       - weward_network
   
networks:
  weward_network:
    driver: bridge
  
    
